### ISSUE TITLE
Opschonen van de code

### ISSUE THREAD

**Issue by TheHunterDog** [SSC-ICT-Innovatie/LearningLion-kamervragen#48]

**Comment by humanintheloop25** [comment]
Vanuit experiment 1 tot ontdekking gekomen dat het wenselijk kan zijn (voor wat meer transparantie) om de code op te schonen tot een simpelere en overzichtelijkere pipeline.

Hiertoe besloten om eerst in een Jupyter notebook te werken om per 'blokje' te kijken wat welk element doet / toevoegt.

Uit deze blokjes konden we later (voor tijdens sprint 1) makkelijker deployments (een soort microservices) vormgeven voor het middleware-platform UbiOps, waar de backend van de uitendelijke tool op zal draaien
